### ISSUE TITLE
Suggestions for additional Matroska MKV tags

### ISSUE THREAD

**Issue by livinggreener** [jamerst/AutoTag#10]
It would be nice if AutoTag could use more of the info available in TMDb for tagging:
(1)Number of episodes in a season: placed in tag with TargetTypeValue of 60 as nested simple tag with name TOTAL_PARTS and string equal to the number of episodes.
(2) TMDB tv show identifier: placed in tag with TargetTypeValue 70 as nested simple tag with name TMDB and string equal to the series identifier "tv/___"
(3)All placed in tag with TargetTypeValue 50 and TargetType EPISODE, as nested simple tags of names: TITLE _(of the episode)_, DIRECTOR, WRITTEN_BY, ACTOR, CHARACTER _(as a nested-tag of ACTOR)_, DATE_RELEASED, DESCRIPTION or SUMMARY, GENRE, all with their respective strings etc...

**Comment by jamerst** [comment]
Some of these require additional requests to be made, so as to not affect the speed of tagging these additional tags will be enabled using a new option, `--extended-tagging`.

Just a few notes regarding 3:
- TITLE - should already be added.
- WRITTEN_BY - doesn't appear to be supported by taglib-sharp
- DATE_RELEASED - not supported by taglib-sharp, closest is DATE_RECORDED
- DESCRIPTION/SUMMARY - this was previously added to COMMENT since this is more commonly shown, it will now be added to both SUMMARY and COMMENT (DESCRIPTION is not supported by taglib-sharp)

If the added tags don't conform to the specification, that's something to bring up with the maintainers of taglib-sharp, I don't particularly want to write my own tagging library.

**Comment by livinggreener** [comment]
> Some of these require additional requests to be made, so as to not affect the speed of tagging these additional tags will be enabled using a new option, --extended-tagging.

Sounds good.


> - TITLE - should already be added.

It is indeed. I noticed it after the fact. For some reason though taglib-sharp is neglecting to give its respective tag `Targets.` `Targets` should be `TargetTypeValue` with string `50` and `TargetType` with string `EPISODE`. However, `Targets` is blank.


> - DESCRIPTION/SUMMARY - this was previously added to COMMENT since this is more commonly shown, it will now be added to both SUMMARY and COMMENT (DESCRIPTION is not supported by taglib-sharp)

Sounds good

> I don't particularly want to write my own tagging library.

I don't blame you.
