### ISSUE TITLE
AutoTag hangs and then breaks the file

### ISSUE THREAD

**Issue by A1ex-N** [jamerst/AutoTag#23]
This has happened to me several times. I run `autotag --extended-tagging -m [movie name]`, autotag prints "found [movie name] on TheMovieDB", and then it just hangs indefinitely. When I press Ctrl-C a few times, it exits, but then my video file is broken and can no longer be played. 

I'm using autotag version 3.5.3, but i'm pretty sure the issue has happened on earlier version too. I'm on Windows 10

**Comment by jamerst** [comment]
I have experienced this issue myself, I believe it is caused by the file itself. My best guess is that it is caused by the layout of the file, if the tags are at the end of the file then the entire file needs to be read and re-written to disk again.

It should complete eventually, though it can take quite a while depending on the file size and storage medium. The only way around it that I have found is to remux the file using something like ffmpeg `ffmpeg -i [file].mkv -c copy [out file].mkv`).

Unfortunately I can't do anything about it in AutoTag itself, the actual tag writing is handled by a library (taglib-sharp).
